# Generated by Django 3.0.7 on 2021-04-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210426_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
